name: App Serviços - HML
values:
  - key: accessToken
    value: ""
    enabled: true
  - key: anuncioId
    value: ""
    enabled: true
  - key: baseUrl
    value: https://PREENCHER-HML
    enabled: true
  - key: brandId
    value: ""
    enabled: true
  - key: categoryId
    value: ""
    enabled: true
  - key: cloudflare_finalUrl
    value: ""
    enabled: true
  - key: cloudflare_uploadPath
    value: ""
    enabled: true
  - key: cloudflare_uploadUrl
    value: ""
    enabled: true
  - key: customerId
    value: ""
    enabled: true
  - key: imageId
    value: ""
    enabled: true
  - key: leadId
    value: ""
    enabled: true
  - key: lojaId
    value: ""
    enabled: true
  - key: modelId
    value: ""
    enabled: true
  - key: noteId
    value: ""
    enabled: true
  - key: opcionalId
    value: ""
    enabled: true
  - key: refreshToken
    value: ""
    enabled: true
  - key: saleId
    value: ""
    enabled: true
  - key: storeId
    value: ""
    enabled: true
  - key: stripeSessionId
    value: ""
    enabled: true
  - key: subscriptionId
    value: ""
    enabled: true
  - key: teamMemberId
    value: ""
    enabled: true
  - key: tipoVeiculoId
    value: ""
    enabled: true
  - key: userDataNascimento
    value: ""
    enabled: true
  - key: userDocumento
    value: ""
    enabled: true
  - key: userId
    value: ""
    enabled: true
  - key: userNome
    value: ""
    enabled: true
  - key: userSenha
    value: ""
    enabled: true
  - key: userSobrenome
    value: ""
    enabled: true
  - key: vehicleId
    value: ""
    enabled: true
color: null
